### ISSUE TITLE
Change plugin name

### ISSUE THREAD

**Issue by achingbrain** [hcoles/classycle-maven-plugin#3]
If you name the plugin `classycle-maven-plugin` instead of `classycle` the you can use the form:

`mvn classycle:analyse`

instead of the longer:

`mvn org.pitest:classycle:analyse`

It's a minor change so I'm happy to submit a pull request for this if preferable.

**Comment by hcoles** [comment]
Thanks - that sounds like a good change. I wasn't aware of the naming convention.
